apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-backupstore
  labels:
    longhorn-test: backupstore
spec:
  containers:
  - name: longhorn-test-backupstore-pod
    image: docker.io/erezhorev/dockerized_nfs_server
    securityContext:
      privileged: true
    args: ["/opt/backupstore"]
