apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-backupstore
  labels:
    longhorn-test: backupstore
spec:
  containers:
  - name: longhorn-test-backupstore-pod
    image: janeczku/nfs-ganesha:latest
    imagePullPolicy: Always
    env:
    - name: EXPORT_ID
      value: "14"
    - name: EXPORT_PATH
      value: /opt/backupstore
    - name: PSEUDO_PATH
      value: /opt/backupstore
    command: ["bash", "-c", "mkdir -p /opt/backupstore && /opt/start_nfs.sh"]
    securityContext:
      capabilities:
        add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
