apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-test
  labels:
    longhorn-test: test-job
spec:
  template:
    metadata:
      name: longhorn-test
    spec:
      containers:
      - name: longhorn-test-pod
        image: yasker/test
        imagePullPolicy: Always
        #args: ["-x", "-s"]
      restartPolicy: Never
  backoffLimit: 1
