apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
  labels:
    longhorn-test: test-job
spec:
  containers:
  - name: longhorn-test-pod
    image: rancher/longhorn-manager-test:215cc88
    imagePullPolicy: Always
    #args: ["-x", "-s", "-k", "test_ha"]
  restartPolicy: Never
